### ISSUE TITLE
[refactor] Try Mobile Kotlin resources for string resources

### ISSUE THREAD

**Issue by ryanw-mobile** [ryanw-mobile/GMap2ICal#76]
This project is small/simple enough to try if this is easy to use.
https://github.com/adrielcafe/lyricist

**Comment by ryanwong-uk** [comment]
The first trial was not positive - the configuration complexity outweighed its value.

**Comment by ryanw-mobile** [comment]
Try moko:
https://medium.com/@avengers14.blogger/kmm-part-2-moko-resource-strings-ebdc65843db0
https://github.com/icerockdev/moko-resources

The grand plan is to eventually port this to a web version (so that I can update files from both web & desktop)

**Comment by ryanw-mobile** [comment]
MoKo Resources gradle setup doesn't work.
It is very scary to look at their issue lists

**Comment by ryanw-mobile** [comment]
Closing this because there will be native support for resources in the upcoming JetBrain Compose - not making sense to have an extra library for this (when the setup is not straightforward)
